version: "3.9"
services:
    backend:
        image: "michaelbuerger/springboot-react-fullstack:3"
        ports:
            - "80:8080"
        restart: always
        environment:
            SPRING_PROFILES_ACTIVE: dev
